#ENC[AES256_GCM,data:KBT49J6PRW/+UO+qqDcm8J3GtsIcENWsSSniRpQPTN/kK3BmykRuQUl6mdsWnOK263Q=,iv:j+gZcj8JqPOgmsrTyaYBbpTKFNsV25vG5wM7j08aFy4=,tag:D8u8UU6QZMbfxDGk9J0AQg==,type:comment]
#ENC[AES256_GCM,data:hof4B8ho7RG9MSm+bSl700PgDZJGY+LyD0xVk12RSsgSnjAlN0E4qPH+Njy/Dw/0d8tFlDKGE+3xdLtRkT93cg9FyqdYaw0=,iv:pLx/vL4rQryDy0JDLjXELGhStnrPeUhgsZqqfvUGRGI=,tag:dS2b7Oi0hYwIv5HVrHI3AA==,type:comment]
#ENC[AES256_GCM,data:Asd9hFhA0WAeYIZN4c+VOcMvAdoQW3ZDU1ovSbQAvUHe8spfoGW06Ou0oTgP/WAqtYnWfUtmoOIf8lpqpdzC1WnU4/L+77keV7o=,iv:YqORMe1y/pffyJHd4DR2RWjITXSYpg6LJPuejLG/ooY=,tag:ilGSo8bwCLlJ5Q+Yq/z7TQ==,type:comment]
#ENC[AES256_GCM,data:dsmYqGqDTUgcAWMHDtQO4RnLG3yJEUzEqSFzt9nphfk3F8DeN9axX29I5Mr8YjKirwmpWXreRAnICpbgbfM=,iv:QBpviykB8QN1eOU7cJeTzd6ohUzQhW/qm4t6KHwcxKw=,tag:LzwltfYLQGEZeBpNX8Qdqg==,type:comment]
tailscale_auth_key: ENC[AES256_GCM,data:shzI3MWmpLx1US9SzIkkZJIMmwKwsOnPdHLwNNXoR4OyphDHb+nZNZym+oaL3fl4IWAdGrL9Db4UO0UvBPM=,iv:xERkj+yH+gVSkCMMLUCUFWz5HNKzIetfawECISrTUHI=,tag:PdRHUyOCflfkAcHMLyIsqw==,type:str]
#ENC[AES256_GCM,data:AfyiFRNHJjcQTW2sqmr4gxgQmEAliCK4rO+sM7WJyKTKgCOZH5WlvHjMRDqmzEJmx6Ed1Sgi+V8U1J6VZCOqMLiJH5RWLj0=,iv:jSBmGJbguCq7X3vUdh7SZkOcKLfIpvb6XdBDAYCkuQQ=,tag:XkcnIF4OVNQU96ywdiJdGA==,type:comment]
#ENC[AES256_GCM,data:correKuvQSoac6OoiE7O0FAonyUMFCgNv+C3yN+i5QhxcLuDJkGENfTD6Yen61fIUegQqdouAwCNY44SDK2Tr3k=,iv:Z9nWWct/vf6+vZi9/tt/6gMuB2ucrgJTUiug1epMZpI=,tag:sfw/Rl0Cgh2EGTJR7GVdOA==,type:comment]
#ENC[AES256_GCM,data:uAX2YYeh9md43H6w6cOdYTz7grYUkbw=,iv:qM9ncPWoPH7B5+f/OEwOjBx18qxTpCGRR0ZRoDT655c=,tag:LLrspXigNF0fOvJvBHTYqQ==,type:comment]
k3s_token: ENC[AES256_GCM,data:dQs6EISWOJl3Xv3laqyf0/pI6WXOrnvN8M+cSQ7x4wde6YkX1ZXGTYyrgyfXk535blKkcxw+yTapLhQTigMHYw==,iv:R9GJkbLGPk4ffAsjCVmKhkCSGJdxwmBFlfLXveCkkfk=,tag:sRLS4a60Zu3KSQ0LU2aCGA==,type:str]
tailscale_oauth_client_id: ENC[AES256_GCM,data:L+KLyiJxhCZO+HICwdZ+q90=,iv:JHv6dq6VXAS2G+HsPB1Pxabkmv3TMVtNCEOicRCp5YU=,tag:klVAvTl75WVDTYhWyT1fQg==,type:str]
tailscale_oauth_client_secret: ENC[AES256_GCM,data:0PduFwHzCtghiujc9uaXBml1Yfg7aiTrEIJD0EYNZdicpAFqYNTTabMNZ+eJ9uUPJ14HRMmvSd2tnV8j2NZWzA==,iv:KC1z1mmGK8gzckFK/osp6L/zi/bLXg0SeN/ynmxtMBc=,tag:Y2O336sbxeCuGkx353eVFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZWM1TGJTNGIrMmxiQll1
            WkI0TmRJZnczenBvUk43NkVNU0VZanRLQm0wCnJ2WjlUUExkNnI3QU9sdmY3c2NI
            SGQ3TzE0MGNyaHgrKzlRMW5qMi9Ra3cKLS0tIG1CcEphTEhGSFJ5ZFJLZWlTbmFJ
            cUxsUUFvcnNiYXd5ZjhacTVXczJzTW8K1vhu8GdK0OFbsce42zbefziWcQQ67iSu
            6epIfZRV188CmxY+D/stvWLWaHjwOUzT3Et49v8QyHXtVLSGn7v6eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4txqd55hxr4gaaxyx360plxjew7695en6ag3h8qnn3wnh2pza5qe85ce0
    lastmodified: "2026-09-22T19:41:21Z"
    mac: ENC[AES256_GCM,data:UuL9M8E91Zoo8k3OVU/6NJWD/gWpuDvAFbzTKlVsXhhkuq3xJaTLsqXDw8cWgnZ8IqUtCb/m8b2q40geKmwiFZ5Nn+arAQKYtlMpl5U4r3cQdqc+cr9sNg8yaQl4Mrs+n7gHRxv420fc3eJDn1De6nfduSEHeZReA7c/L2AddAk=,iv:x/FgdW1ejAgUo3u2ebzbZKf5vN2hNcF46xmvqq0/QCE=,tag:JLnfusvwWZ4MxW4BVJX1SQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
