#ENC[AES256_GCM,data:l2lZ4wMJMifwnZrSaY2Q62FSbomUfUgixYIC2w+Kjja0gG4yB1ckULPnwejqSBQ0nI8=,iv:XgIU/v/uHYIrA+pQC32erpCnLSLYBM24rPXsIgdhRhU=,tag:w4mvZ3fXAeIljOLHavFuOg==,type:comment]
#ENC[AES256_GCM,data:lewuVXtxYGMtirA8oyqfHh457Ow4zvGUqRMA+S2cGAwmXgEepCT6VV/VzZVFWh2+JmwHUfbrs/hn33A1EAIIV4dJO/8MFds=,iv:jDshajtzfpAReS1X1MR7w6bjLfNV+i0Qi6PlglLAmQM=,tag:OgWsrnkESbKCwNyUmAO5ow==,type:comment]
#ENC[AES256_GCM,data:ls/2FrZANXYAG7oSQl+8JhxXJkJ3Mt7OEhliI/9ADw5IVLVJXsfT5+k/0v0/mOttD+kl+qSVcU//r3xlgng7m14NNK8BkfVBKaI=,iv:o0y48xyx3snS5WcNg9YAbddI66byRy6CeYaKkwiA0SA=,tag:OgH/hFKVozuAunUJpEpfPA==,type:comment]
#ENC[AES256_GCM,data:srq8FGXXSVQDmlRt5f3zYsMRlYe1QIuWLdSD2c6vb9pjFDJpgFzXIsKBZZ1YC2vlB6Cprg7KBQNYQb84/AE=,iv:lWDtFNlFkEzPxex1vSzPDhcbVLGuEVJD7ZkSkUIrMlo=,tag:nOtPxuBqn7vrkrNOq79rLg==,type:comment]
tailscale_auth_key: ENC[AES256_GCM,data:MGNZMgjFEObAjCjwBUEC+BNRRtfLTIoNAn9E5E0rxwXIs8l76Rk0iW3lx+fXGp6AyEU/xYUfQugOjUy7Ye8=,iv:O2bZLGhJNuqfS2UZI3eLkIegPHihY7gH8n+KreI4frw=,tag:G1HSH5aeftPQkafrsaN3sQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwelBJM2lUaG90NUxvU3lz
            aXpGa0dVQVVicW9BR2FWTDUrN2k2WjgvV2xZCk1wbGdpeVBSeGsybzNRWnA4VlFW
            cUdwenhOZGszSnFsOFErUGk3SFp3alUKLS0tIGhCMnNSMGVvRWJFY3FBQXcya05O
            cTUwY0U1dlVkb1lzelhMRTFoUXhBV1kK0pUwvhXfgK3GAcdb5nh6rn/2PyKHnR7X
            da//lLxCoU3khLRqfTuaPHGiERMqVIqQPoFje7JX8GCMshpItMr7bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4txqd55hxr4gaaxyx360plxjew7695en6ag3h8qnn3wnh2pza5qe85ce0
    lastmodified: "2026-09-18T13:22:38Z"
    mac: ENC[AES256_GCM,data:hYhE0l1kRPpJktbXYbKHPmBdt7QCCTTNuu8ysr/1GT1TyAolkATgBNzoH2k5oAlP3Z7a5NfEwrLPJnJLnxcKfnvkysQ3da6awsD1pd1GoCi6Dr4zQXqi49nHPxMxppU4i9ArRNNhljN427MI7bg5jUcNJhyMniN5kQeJQsKQY8M=,iv:55W4g2SjfO17m6aRTc28+qq5Ctv9nuFxZLARQbn9npU=,tag:ilQ3h4vZHgkftufZj22atA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
